language: php
php:
  - 5.2
  - 5.4
  - 5.3

#env:
# - DB=mysql

#before_script:
# - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

script: phpunit tests

notifications:
  email:
    - scott@griepentrog.com

