<?php
// generated by make.php - do not edit

/**
 * convenience constructor functions
 * @package poof
 */

function arbase()
{
    $that=new arbase();
    return $that;
}

function ardir($path=false)
{
    $that=new ardir($path);
    return $that;
}

function arfile($file)
{
    $that=new arfile($file);
    return $that;
}

function arquery($query)
{
    $that=new arquery($query);
    return $that;
}

function arrecursivedir($path=false)
{
    $that=new arrecursivedir($path);
    return $that;
}

function audigest($realm,$users,$fail=false)
{
    $that=new audigest($realm,$users,$fail);
    return $that;
}

function bad_daemon()
{
    $that=new bad_daemon();
    return $that;
}

function dbarray($table)
{
    $that=new dbarray($table);
    return $that;
}

function dbbase()
{
    $that=new dbbase();
    return $that;
}

function dbcsv($file)
{
    $that=new dbcsv($file);
    return $that;
}

function dbcsv_daemon($path)
{
    $that=new dbcsv_daemon($path);
    return $that;
}

function dbflat($file,$fields)
{
    $that=new dbflat($file,$fields);
    return $that;
}

function dbini($file)
{
    $that=new dbini($file);
    return $that;
}

function dbpoofsite()
{
    $that=new dbpoofsite();
    return $that;
}

function dbwhere($db,$where)
{
    $that=new dbwhere($db,$where);
    return $that;
}

function event()
{
    $that=new event();
    return $that;
}

function gtalk_daemon()
{
    $that=new gtalk_daemon();
    return $that;
}

function mlbase($text=false)
{
    $that=new mlbase($text);
    return $that;
}

function mlscrape($text=false)
{
    $that=new mlscrape($text);
    return $that;
}

function pfbase()
{
    $that=new pfbase();
    return $that;
}

function pfdaemon($name,$path=false)
{
    $that=new pfdaemon($name,$path);
    return $that;
}

function pfdaemonserver($error)
{
    $that=new pfdaemonserver($error);
    return $that;
}

function pfgtalk()
{
    $that=new pfgtalk();
    return $that;
}

function pfsingleton()
{
    $that=new pfsingleton();
    return $that;
}

function sidiscern($name=false,$data=false,$time=false)
{
    if (empty($GLOBALS['sidiscern']))
        return $GLOBALS['sidiscern']=new sidiscern($name,$data,$time);
    else
        return $GLOBALS['sidiscern']($name,$data,$time);
}

function sierror($error=false)
{
    if (empty($GLOBALS['sierror']))
        return $GLOBALS['sierror']=new sierror($error);
    else
        return $GLOBALS['sierror']($error);
}

function sitest($value)
{
    if (empty($GLOBALS['sitest']))
        return $GLOBALS['sitest']=new sitest($value);
    else
        return $GLOBALS['sitest']($value);
}

function uialert($class=false,$text=false)
{
    $that=new uialert($class,$text);
    return $that;
}

function uiarticle($class=false)
{
    $that=new uiarticle($class);
    return $that;
}

function uiaside($class=false)
{
    $that=new uiaside($class);
    return $that;
}

function uibadge($class=false)
{
    $that=new uibadge($class);
    return $that;
}

function uiblockquote()
{
    $that=new uiblockquote();
    return $that;
}

function uibutton($text=false,$href=false)
{
    $that=new uibutton($text,$href);
    return $that;
}

function uicarousel($list=false)
{
    $that=new uicarousel($list);
    return $that;
}

function uicodemirror($text)
{
    $that=new uicodemirror($text);
    return $that;
}

function uicollapse($list)
{
    $that=new uicollapse($list);
    return $that;
}

function uicontainer($class=false)
{
    $that=new uicontainer($class);
    return $that;
}

function uicontainerfluid($class=false)
{
    $that=new uicontainerfluid($class);
    return $that;
}

function uidaterange()
{
    $that=new uidaterange();
    return $that;
}

function uidebug($what=false)
{
    $that=new uidebug($what);
    return $that;
}

function uidiv($class=false)
{
    $that=new uidiv($class);
    return $that;
}

function uidivider()
{
    $that=new uidivider();
    return $that;
}

function uidropdown($text,$list=false)
{
    $that=new uidropdown($text,$list);
    return $that;
}

function uieditable($db,$fields=NULL)
{
    $that=new uieditable($db,$fields);
    return $that;
}

function uieditrecord($db,$fields=NULL)
{
    $that=new uieditrecord($db,$fields);
    return $that;
}

function uielement()
{
    $that=new uielement();
    return $that;
}

function uifooter($class=false)
{
    $that=new uifooter($class);
    return $that;
}

function uiform($fields=false,$record=false,$style=false)
{
    $that=new uiform($fields,$record,$style);
    return $that;
}

function uigittip($username)
{
    $that=new uigittip($username);
    return $that;
}

function uigoogleanalytics($account,$domain=false)
{
    $that=new uigoogleanalytics($account,$domain);
    return $that;
}

function uiheader($class=false)
{
    $that=new uiheader($class);
    return $that;
}

function uiheading($level,$text=false)
{
    $that=new uiheading($level,$text);
    return $that;
}

function uihelpicon($text)
{
    $that=new uihelpicon($text);
    return $that;
}

function uihero()
{
    $that=new uihero();
    return $that;
}

function uihgroup($class=false)
{
    $that=new uihgroup($class);
    return $that;
}

function uihtml($html)
{
    $that=new uihtml($html);
    return $that;
}

function uiicon($name)
{
    $that=new uiicon($name);
    return $that;
}

function uiiconbutton($icon,$name=false)
{
    $that=new uiiconbutton($icon,$name);
    return $that;
}

function uiiframe($src)
{
    $that=new uiiframe($src);
    return $that;
}

function uiimage($src)
{
    $that=new uiimage($src);
    return $that;
}

function uiinput_base($attr=false,$valid)
{
    $that=new uiinput_base($attr,$valid);
    return $that;
}

function uiinput_button($attr=false)
{
    $that=new uiinput_button($attr);
    return $that;
}

function uiinput_cancel($attr=false)
{
    $that=new uiinput_button($attr);
    return $that;
}

function uiinput_checkbox($attr=false)
{
    $that=new uiinput_checkbox($attr);
    return $that;
}

function uiinput_radio($attr=false)
{
    $that=new uiinput_radio($attr);
    return $that;
}

function uiinput_select($attr=false)
{
    $that=new uiinput_select($attr);
    return $that;
}

function uiinput_text($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_password($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_hidden($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_image($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_reset($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_submit($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_color($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_date($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_datetime($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_datetime_local($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_email($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_month($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_number($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_range($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_search($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_tel($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_time($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_url($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_week($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_key($attr=false)
{
    $that=new uiinput_text($attr);
    return $that;
}

function uiinput_textarea($attr=false)
{
    $that=new uiinput_textarea($attr);
    return $that;
}

function uilabel($text=false)
{
    $that=new uilabel($text);
    return $that;
}

function uilead($text)
{
    $that=new uilead($text);
    return $that;
}

function uilegend($text=false)
{
    $that=new uilegend($text);
    return $that;
}

function uilink($href,$text=false)
{
    $that=new uilink($href,$text);
    return $that;
}

function uilist($list=false)
{
    $that=new uilist($list);
    return $that;
}

function uilongpoll()
{
    $that=new uilongpoll();
    return $that;
}

function uinav($class=false)
{
    $that=new uinav($class);
    return $that;
}

function uinavbar($brand=false,$menu=false)
{
    $that=new uinavbar($brand,$menu);
    return $that;
}

function uinavlist($list=false)
{
    $that=new uinavlist($list);
    return $that;
}

function uipage($meta='')
{
    $that=new uipage($meta);
    return $that;
}

function uipanel($name)
{
    $that=new uipanel($name);
    return $that;
}

function uiparagraph($text=false)
{
    $that=new uiparagraph($text);
    return $that;
}

function uipopover($text)
{
    $that=new uipopover($text);
    return $that;
}

function uipre($text)
{
    $that=new uipre($text);
    return $that;
}

function uirelead($trackingid)
{
    $that=new uirelead($trackingid);
    return $that;
}

function uirow($class=false)
{
    $that=new uirow($class);
    return $that;
}

function uirowfluid($class=false)
{
    $that=new uirowfluid($class);
    return $that;
}

function uiscript($code)
{
    $that=new uiscript($code);
    return $that;
}

function uisection($class=false)
{
    $that=new uisection($class);
    return $that;
}

function uispan($number,$offset=false)
{
    $that=new uispan($number,$offset);
    return $that;
}

function uitabbable($list)
{
    $that=new uitabbable($list);
    return $that;
}

function uitable($db,$fields=NULL)
{
    $that=new uitable($db,$fields);
    return $that;
}

function uitheme($page)
{
    $that=new uitheme($page);
    return $that;
}

function uitooltip($text)
{
    $that=new uitooltip($text);
    return $that;
}

function uiwell($class=false)
{
    $that=new uiwell($class);
    return $that;
}

function uiyoutube($url,$width=640,$height=false)
{
    $that=new uiyoutube($url,$width,$height);
    return $that;
}
