<?php
// generated by make.php - do not edit

function arbase()
{
	return new arbase();
}

function ardir($path=false)
{
	return new ardir($path);
}

function audigest($realm,$users,$fail=false)
{
	return new audigest($realm,$users,$fail);
}

function dbbase()
{
	return new dbbase();
}

function dbcsv($file)
{
	return new dbcsv($file);
}

function event()
{
	return new event();
}

function test($one,$two=false)
{
	return new test($one,$two);
}

function uiblockquote()
{
	return new uiblockquote();
}

function uibutton($text,$href=false)
{
	return new uibutton($text,$href);
}

function uicarousel($list=false)
{
	return new uicarousel($list);
}

function uicodearea($text)
{
	return new uicodearea($text);
}

function uicollapse($list)
{
	return new uicollapse($list);
}

function uicontainer($class=false)
{
	return new uicontainer($class);
}

function uidaterange()
{
	return new uidaterange();
}

function uidebug($what=false)
{
	return new uidebug($what);
}

function uidiv($class)
{
	return new uidiv($class);
}

function uidivider()
{
	return new uidivider();
}

function uidropdown($text,$list=false)
{
	return new uidropdown($text,$list);
}

function uielement()
{
	return new uielement();
}

function uiform()
{
	return new uiform();
}

function uiheader($level,$text=false)
{
	return new uiheader($level,$text);
}

function uihero()
{
	return new uihero();
}

function uihtml($html)
{
	return new uihtml($html);
}

function uiicon($name)
{
	return new uiicon($name);
}

function uiimage($src)
{
	return new uiimage($src);
}

function uilead($text)
{
	return new uilead($text);
}

function uilink($href,$text=false)
{
	return new uilink($href,$text);
}

function uilist($list=false)
{
	return new uilist($list);
}

function uinavbar()
{
	return new uinavbar();
}

function uinavlist($list=false)
{
	return new uinavlist($list);
}

function uipage($meta)
{
	return new uipage($meta);
}

function uiparagraph($text=false)
{
	return new uiparagraph($text);
}

function uipopover($text)
{
	return new uipopover($text);
}

function uipre($text)
{
	return new uipre($text);
}

function uiscript($code)
{
	return new uiscript($code);
}

function uitabbable($list)
{
	return new uitabbable($list);
}

function uitable($db,$fields=NULL)
{
	return new uitable($db,$fields);
}

function uitooltip($text)
{
	return new uitooltip($text);
}
