<?php

class uipage extends uiElement
{
    private $ui_meta;
    private $ui_styles;
    private $ui_prescripts;
    private $ui_postscripts;
    private $ui_headscripts;
    private $ui_readyscripts;

    public function __construct($meta)
    {
        parent::__construct();
        $this->ui_tag="body";
        $this->ui_meta=$meta;

        $this->ui_styles=array();
        $this->ui_prescripts=array();
        // jquery always goes first!
        $this->ui_postscripts=array();
        $this->ui_headscripts=array();
        $this->ui_readyscripts=array();

        if (!is_array($meta))
            $this->ui_meta=array('title'=>$meta);


        // activate the theme (it calls back to add elements)
        uiTheme($this);
    }
    public function Stylesheet($name,$file)
    {
        $this->ui_styles[$name]=$file;
    }
    public function PreScript($name,$file)
    {
        $this->ui_prescripts[$name]=$file;
    }
    public function PostScript($name,$file)
    {
        $this->ui_postscripts[$name]=$file;
    }
    public function HeadScript($name,$code)
    {
        $this->ui_headscripts[$name]=$code;
    }
    public function ReadyScript($name,$code)
    {
        $this->ui_readyscripts[$name]=$code;
    }
    public function GenerateStyles()
    {
        global $POOF_URL;

        $output='';

        foreach ($this->ui_styles as $style)
            $output.=$this->Tag("link href=\"".
                poof_url("css/$style").
                "\" rel=\"stylesheet\"");

        return($output);
    }
    public function GeneratePreScripts()
    {
        global $POOF_URL;
        $output='';
        $head='';

        foreach ($this->ui_prescripts as $script)
            $output.=$this->Tag("script src=\"".
                poof_url("js/$script").
                "\"");

        $head='';
        foreach ($this->ui_headscripts as $code)
            $head.=" ".$code."\n";

        if (!empty($head))
            $output.=$this->Tag("script type=\"text/javascript\"",$head);

        return($output);
    }
    public function GeneratePostScripts()
    {
        global $POOF_URL;
        $output='';

        foreach ($this->ui_postscripts as $script)
            $output.=$this->Tag("script src=\"".
                poof_url("js/$script").
                "\"");

        // active the js components
        $ready='';
        foreach ($this->ui_readyscripts as $code)
            $ready.=" ".$code."\n";
/*
    \$('.nav-tabs').button();
    \$('#{$this->ui_id}').bind('contextmenu',function(e){
        if (e.ctrlKey) {
            alert('right click '+e.toElement.id);
            console.log(\"rightclick=%o\",e);

            return false;
        }
    })
*/
        if (!empty($ready))
        $output.=$this->Tag("script type=\"text/javascript\"",
            "\$(document).ready(function(){\n".
            $ready.
            "});\n"
        );

        return($output);
    }
    public function GenerateMeta()
    {
        $output='';

        foreach ($this->ui_meta as $name => $content)
            if ($name!='title')
                $output.=$this->Tag("meta name=\"$name\" content=\"$content\"");
                //$output.=$this->Indent()."<meta name=\"$name\" content=\"$content\">";
        return($output);
    }

    public function __toString()
    {
        if (!empty($_SERVER['REQUEST_METHOD']) && $_SERVER['REQUEST_METHOD']=='POST')
        {
            $_SERVER['REQUEST_METHOD']='post-handled';
            siDiscern()->Event('post');
            if ($this->PassToPostHandler())
                return('');
        }

        // allow tree elements to pass scripts/css up to page generator
        siDiscern()->Event('pregen');
        $this->PreGenerateWalk($this);

        siDiscern()->Event('generate');
        return("<!DOCTYPE html>".
            $this->Tag("html lang=\"en\"",
                $this->Tag("head",
                    "\n<!-- Generated by POOF (http://poof.stg.net) -->".
                    $this->Tag("title",htmlentities($this->ui_meta['title'])).
                    $this->Tag("meta charset=\"utf-8\"").
                    $this->GenerateMeta().
                    $this->GenerateStyles().
                    $this->GeneratePreScripts()
                ).
                $this->Tag($this->GenerateTag(),
//                    print_r($_SERVER,true).
//                    print_r($_GET,true).
//                    print_r($_POST,true).
                    $this->GenerateContent()
                ).
                $this->GeneratePostScripts()
            )
            .(siDiscern()->Event('output')?'':'')
        );
    }

}
